from enum import Enum


class EnvironmentKeys(Enum):
    CONNECTION_STRING = "CONNECTION_STRING"
    OS = "OS"
    MONGO_URI = "MONGO_URI"
    EMAIL = "EMAIL"
    EMAIL_PASSWORD = "EMAIL_PASSWORD"
    SECRET_KEY = "SECRET_KEY"
    ALGORITHM = "ALGORITHM"
    OTP_SECRET = "OTP_SECRET"

class TestEnvironmentKeys(Enum):
    CONNECTION_STRING = "CONNECTION_STRING"
    SECRET_KEY = "SECRET_KEY"
    PRIVATE_KEY = "PRIVATE_KEY"
