name: Lint and Build Next.js app

on:
  push:
    paths:
      - 'app/**'    # only run if files in app/ change
  pull_request:
    paths:
      - 'app/**'    # also run on PRs that modify app/ files

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: app
        run: npm ci

      - name: Run linter
        working-directory: app
        run: npm run lint

      - name: TypeScript type check
        working-directory: app
        run: npx tsc --noEmit

      - name: Build Next.js app
        working-directory: app
        run: npm run build